name: Cheerity
favicon: null
layout_spectrum: 0.50724
typography_spectrum: 0.41706
title: Cheerity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71571504-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff1e35'
    - '#00f0ee'
    - '#0b25fe'
    - '#dedee0'
    - '#ff8a82'
  brandStrength: 0.5465792117174715
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
