title: Cheerity
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4375
  lightness: 0.75
  brandStrength: 0.9964158
  brandColors:
    - '#262215'
    - '#ADA26C'
    - '#67645B'
    - '#7787A3'
    - '#ACCFFF'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-71571504-1
  facebook: null
favicon: null
name: Cheerity
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.41706
layout_spectrum: 0.50724
