name: Cheerity
favicon: null
layout_spectrum: 0.5897651286795735
typography_spectrum: 0.7122291673440486
title: Cheerity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5465792117174715
  lightness: 0.6689819728489965
  saturation: 0.3477333781775087
  rhythmicContrast: 0.3033051327802241
purpose: []
